/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Pub.h"
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "hDrv.h"
#include "lwip_demo.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;

void test0_cpu1(void *pvParameters)
{
    while (1)
    {
        //Ifx_print1("t0 %d \r\n", itimes++);
        multi_can_send_msg(0);
        vTaskDelay(1);
    }
}

void test1_cpu1(void *pvParameters)
{
    while (1)
    {
        //Ifx_print1("t1 %d \r\n", itimes++);
        multi_can_send_msg(1);
        vTaskDelay(1);
    }
}

void test2_cpu1(void *pvParameters)
{
    while (1)
    {
        //Ifx_print1("t2 %d \r\n", itimes++);
        multi_can_send_msg(2);
        vTaskDelay(1);
    }
}

void test3_cpu1(void *pvParameters)
{
    while (1)
    {
        //Ifx_print1("t3 %d \r\n", itimes++);
        multi_can_send_msg(3);
        vTaskDelay(1);
    }
}

void test4_cpu1(void *pvParameters)
{
    while (1)
    {
        //Ifx_print1("t4 %d\r\n", itimes++);
        multi_canr_send_msg(0);
        vTaskDelay(1);
    }
}

void test5_cpu1(void *pvParameters)
{
    while (1)
    {
        //Ifx_print1("t5 %d \r\n", itimes++);
        multi_canr_send_msg(1);
        vTaskDelay(1);
    }
}

void test6_print(void *pvParameters)
{
    while (1)
    {
        //alert_3 = hwNode4->SR.U;
        Ifx_print1("- -**- %d %d %d %d %d %d -**- -0x%x 0x%x 0x%x 0x%x\r\n",
                   itimes_can0_rcv, itimes_can1_rcv, itimes_can2_rcv, itimes_can3_rcv, itimes_can4_rcv, itimes_can5_rcv,
                   stat_0, stat_1, stat_2, stat_3);
        vTaskDelay(1000);
    }
}

SemaphoreHandle_t g_can_restart_phore = NULL;
//when can error ,this task restart can node
void multi_can_restart(void *pvParameters)
{
    g_can_restart_phore = xSemaphoreCreateCounting(2, 0);
    for (;;)
    {
        //Ifx_print("multi_can_restart g_can_restart_phore\r\n");
        xSemaphoreTake(g_can_restart_phore, portMAX_DELAY);
        switch (restart_num)
        {
        case 0:
        {
            multi_can_node0_init();
            break;
        }
        case 1:
        {
            multi_can_node1_init();
            break;
        }
        case 2:
        {
            multi_can_node2_init();
            break;
        }
        case 3:
        {
            multi_can_node3_init();
            break;
        }
        case 4:
        {
            multi_can_node4_init();
            break;
        }
        case 5:
        {
            multi_can_node5_init();
            break;
        }
        default:
            break;
        }
        vTaskDelay(1000);//must delay
    }
}

int core1_main(void)
{
    int idelay = 0;
    BaseType_t xReturn;
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG1 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    idelay = 50000000;
    while (idelay--)
        ;

    init_uart_module1();
    multi_can_module_init();
    multi_can_node0_init();
    multi_can_node1_init();
    multi_can_node2_init();
    multi_can_node3_init();
    multi_canr_module_init();
    multi_can_node4_init();
    multi_can_node5_init();

    //test_eth_bare();

    xReturn = xTaskCreate(test0_cpu1, "test0_cpu1", 1024, NULL, 3, NULL);
    Ifx_print1("xReturn test0_cpu1 %x \r\n", xReturn);
    xReturn = xTaskCreate(test1_cpu1, "test1_cpu1", 1024, NULL, 3, NULL);
    Ifx_print1("xReturn test1_cpu1 %x \r\n", xReturn);
    xReturn = xTaskCreate(test2_cpu1, "test2_cpu1", 1024, NULL, 3, NULL);
    Ifx_print1("xReturn test2_cpu1 %x \r\n", xReturn);
    xReturn = xTaskCreate(test3_cpu1, "test3_cpu1", 1024, NULL, 3, NULL);
    Ifx_print1("xReturn test3_cpu1 %x \r\n", xReturn);
    xReturn = xTaskCreate(test4_cpu1, "test4_cpu1", 1024, NULL, 3, NULL);
    Ifx_print1("xReturn test4_cpu1 %x \r\n", xReturn);
    xReturn = xTaskCreate(test5_cpu1, "test5_cpu1", 1024, NULL, 3, NULL);
    Ifx_print1("xReturn test5_cpu1 %x \r\n", xReturn);
    xReturn = xTaskCreate(test6_print, "test6_print", 1024, NULL, 3, NULL);
    Ifx_print1("xReturn test6_print %x \r\n", xReturn);
    xReturn = xTaskCreate(multi_can_restart, "multi_can_restart", 1024, NULL, 4, NULL);
    Ifx_print1("xReturn multi_can_restart %x \r\n", xReturn);

    while (1)
    {
        //multi_can_send_msg(3);
        //multi_canr_send_msg(0);
    }
    return (1);
}
